### ISSUE TITLE
Form store error: method not allowed

### ISSUE THREAD

**Issue by d-sko** [bgaze/bootstrap-form#1]
Hello,

first: thank you for this useful library! It really simplifies things.

I have an issue with using model binding with store and update. This is how I open the form:
```php
/*[...]*/
@open(['model' => $news, 'update' => 'Backend\NewsController@update', 'store' => 'Backend\NewsController@store'])
/*[...]*/
```
Now if I try to save a new record I get the following error:
```
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException thrown with message "The POST method is not supported for this route. Supported methods: GET, HEAD, PUT, PATCH, DELETE."
```
this is the definition for this route:
```php
Route::group(['prefix' => 'backend', 'as' => 'backend.', 'namespace' => 'Backend'], function() {
    /* [...] */
    Route::group(['as' => 'contents.'], function() {
        Route::resource('news', 'NewsController');
    });
});
```
Updating an existing record works. Am I missing something? I'm using Laravel 6.5.0.

Edit: I can create new records when I use a different form `@open(['action' => 'Backend\NewsController@store'])`, but I'd like to use the update-/store-option so I can use the same template for both actions.

**Comment by bgaze** [comment]
Hi @d-sko 
Thanks for your feedback.

I'm debugging your issue right now.

The only way I manage to reproduce it was by passing `null` into the `$news` variable on create view:

```php
public function create()
{
    return view('your.create.view.name', ['news' => null]);
}
```

As explained [in the doc](https://www.bgaze.fr/bootstrap-form#model-binding), an instance of `Illuminate\Database\Eloquent\Model` **must** be provided in order to activate model binding:

```php
public function create()
{
    return view('your.create.view.name', ['news' => new News()]);
}
```

Does this solve your issue ?

**Comment by d-sko** [comment]
Yes, this solved my issue, so it was just me failing at RTFM :wink:. Thank you very much!

**Comment by bgaze** [comment]
No problem 😄
