### ISSUE TITLE
Same page forms with different error bags 

### ISSUE THREAD

**Issue by RobHawk90** [bgaze/bootstrap-form#13]
Is there a way config an error bag for a form?

**Comment by bgaze** [comment]
Hi @RobHawk90 

This is indeed missing in doc, but you can pass your custom bag name into form options under the `error_bag` key.

**Comment by RobHawk90** [comment]
> Hi @RobHawk90
> 
> This is indeed missing in doc, but you can pass your custom bag name into form options under the `error_bag` key.

It worked! Thanks!
