### ISSUE TITLE
Checkboxes not getting checked by default

### ISSUE THREAD

**Issue by speedlist** [bgaze/bootstrap-form#15]
@checkbox('recently_sold','Include recently sold listings',1,true,['switch'=>true])

Not sure why but when It try to check a checkbox by default, it doesn't have that state.   Am I doing something wrong?

**Comment by bgaze** [comment]
Hi @speedlist 

Sorry for this late answer.

I've not be able to reproduce your problem : from a model binded  form, a regular form as well as a standalone field, forcing the `checked` parameter produce expected result.

If this problem occurs to you again, can you please check that it's not an issue with Bootstrap switches (I've already had problems with them in the past) :

- is the `checked` attribute present in generated source code ?
- does the problem still present when turning off the `switch` option ?

Thanks

**Comment by speedlist** [comment]
```
<div class="test form-group" id="recently_sold_group">
    <div>
        <div class="custom-control custom-switch"><input id="recently_sold" class="custom-control-input"
                                                         name="recently_sold" type="checkbox" value="1"><label
                for="recently_sold" class="custom-control-label">Include recently sold listings</label></div>
    </div>
</div>  
```

IS what's generated, not exactly sure what I'm doing wrong here.

**Comment by edrinshrike** [comment]
If setting Checked to true isn't working for you, try setting it to the value of the checkbox, which in this case would be "1".

`@checkbox('recently_sold','Include recently sold listings',1,1,['switch'=>true])`

I tested it both ways and it worked each time, but perhaps you'll have better luck assigning the actual value of the checkbox you want checked.

**Comment by speedlist** [comment]
My bad, I just realized on that particular form I had used a request->flash making the form believe that those attributes were not set by default
