### ISSUE TITLE
Form Groups have a class of "test"

### ISSUE THREAD

**Issue by edrinshrike** [bgaze/bootstrap-form#16]
As the title states, it seems like you accidentally left some test data in the code, so Form Groups are gaining a class of "test". It shouldn't affect anything unless someone has a custom class with that name, but it's still probably something you don't want there. This can even be seen in the examples in the documentation.

**Comment by bgaze** [comment]
Thanks for pointing out that @edrinshrike.

In fact I've made a fix for that months ago and I forgot to publish it, shame on me.  
I've just published it, please update to [v1.0.9](https://github.com/bgaze/bootstrap-form/releases/tag/v1.0.9).

Please note that the mistake was made into the package config file. So if it was published in your app, you'll also need to [manually fix](https://github.com/bgaze/bootstrap-form/commit/f1df402cf92b9ee9a71cd8ba176c8adeda5c87d7) the published version.
