### ISSUE TITLE
'Required' attribute on radio input group has no effect

### ISSUE THREAD

**Issue by edrinshrike** [bgaze/bootstrap-form#2]
[Setting any radio input to required](https://html.spec.whatwg.org/multipage/input.html#the-required-attribute) should set the whole group to be required, but when I add 'required' to the options on a radio group, it doesn't have any effect. Ideally, adding ['required' => true] to a radio input group would set the first option to required.

**Comment by bgaze** [comment]
Thanks @edrinshrike for your feedback

This was indeed a bug: when buidling check group, HTML attributes weren't passed to children inputs :-(

I've fixed that and increased version to v1.0.2
