### ISSUE TITLE
Ability to add class to all input labels

### ISSUE THREAD

**Issue by ronvdberkmortel** [bgaze/bootstrap-form#3]
Is there or could there be a way to automatically add a class to all labels, except functional labels for checkboxes/radios? It would be nice to add the 'form-label' class to all form group labels, instead of having to specify the label and its class for each input.

**Comment by bgaze** [comment]
Hi @ronvdberkmortel 

This is not possible and not planned.

I've worked a bit in that way when building the lib, but I've renounced: if I do it for labels, why not for others form groups elements ?

That would bring a complexity layer that I want to avoid, and I want to stick as much as possible with standard Bootstrap markup.

So I've decided to provide attributes customization for the input and the group only.

However, I agree that it would be handy to be able to define app/form wide options for form groups.
I'm going to implement that very soon, so you'll be able to add a class to all your forms groups, and to access easily to labels they contain.

**Comment by ronvdberkmortel** [comment]
Thank you for your reply. Your point is clear and I understand why it could create too much customization.

In the situation I mentioned above, the issue appears easily solved by using the following CSS selector and using that to apply the same CSS as the desired class.

`.form-group > label`

**Comment by bgaze** [comment]
Hi @ronvdberkmortel 

As discussed, I've implemented a way to define app/form wide options for form groups.

Please see [v1.0.4 release](https://github.com/bgaze/bootstrap-form/releases/tag/v1.0.4).
