### ISSUE TITLE
Feedback on input groups is not visible

### ISSUE THREAD

**Issue by ronvdberkmortel** [bgaze/bootstrap-form#4]
By default, feedback is not visible in Bootstrap 4. Feedback becomes visible when adjacent to an element with the class 'is-invalid'. This works for normal inputs, but input groups have a parent div which prevents the feedback from showing up.

![ea58edd8788ec6fb1fecd4668aa926fb](https://user-images.githubusercontent.com/11784967/69900446-bbbb4300-1373-11ea-830a-54312dd661db.png)

The Bootstrap documentation avoids this issue by appending the feedback to the input instead of the form-group, keeping the feedback inside the input-group. Perhaps this functionality could be added to the feedback for input-group elements.

![5c0a310ccfb6f5e377806ad2df330424](https://user-images.githubusercontent.com/11784967/69900481-36845e00-1374-11ea-8a81-7baa5aea4dba.png)

**Comment by bgaze** [comment]
Thanks for your feedback @ronvdberkmortel, I'll correct that soon

**Comment by bgaze** [comment]
Hi @ronvdberkmortel 

Sorry for this late feedback, I got a lot of work this days :-/

I had the same issue with checkboxes & radios groups. Adding the error feedback into the group itself was messing with global form display when using horizontal and inline layout.

I fixed that by forcing the error display with a `d-block` class.
I did the same for input groups, please see `v1.0.3` release.

Not ideal I know, but it works. 
I'm trying to stick as much as possible to Bootstrap default markup, this is one of the few exceptions...

**Comment by ronvdberkmortel** [comment]
That seems like a fair way of dealing with the issue! Thank you for your effort.
