### ISSUE TITLE
@hidden 'name' argument only adds name attribute, but no id attribute

### ISSUE THREAD

**Issue by edrinshrike** [bgaze/bootstrap-form#5]
I couldn't tell if this was intentional, but every other input creates a Name and an ID attribute when you give a name argument, but @hidden only creates the name attribute.

**Comment by bgaze** [comment]
Hi @edrinshrike,

Thanks for your feedback.
Hidden method is just an alias to Collective HTML function, that's why it works this way.

But it would make sense to make it work as others methods.
I'll try to publish a fix for that tonight.

**Comment by bgaze** [comment]
Hi @edrinshrike,

I've published a fix, please see [v1.0.5 release](https://github.com/bgaze/bootstrap-form/releases/tag/v1.0.5).

Thank again for your feedback.

**Comment by bgaze** [comment]
Hi @edrinshrike ,

Does that patch fixed your issue ?

Thanks :-)

**Comment by edrinshrike** [comment]
Yes, this appears to be fixed now. Thanks for the quick fix.
