### ISSUE TITLE
Radio and checkbox choice labels broken

### ISSUE THREAD

**Issue by edrinshrike** [bgaze/bootstrap-form#6]
Something in release 1.0.4 broke the labels of checkbox and radio choices. They are all inheriting the group name, so if a radio group is named "Colors", all radio choices will be labeled "Colors" as well.

**Comment by edrinshrike** [comment]
Problem appears to be in Support/Input.php, line 167.
`$this->label = str_replace('_', ' ', Str::ucfirst(Str::lower(Str::title($this->name))));`
should be
`$this->label = str_replace('_', ' ', Str::ucfirst(Str::lower(Str::title($this->label))));`

I don't know if that's the ONLY place the problem lies, but making that change locally fixed it for me. I'm not knowledgeable enough with github to make a pull request.

**Comment by bgaze** [comment]
Oups 🤕
Thanks for your feedback @edrinshrike, I'll fix that tonight

**Comment by bgaze** [comment]
Hi @edrinshrike 

I can't really unterstand you what appens here :-/
PHP acting weird when mixing inheritance and magic methods...

I've fixed the issue, please see release [v1.0.6](https://github.com/bgaze/bootstrap-form/releases/tag/v1.0.6)

**Comment by bgaze** [comment]
Hi @edrinshrike ,

Does that patch fixed your issue ?

Thanks :-)

**Comment by edrinshrike** [comment]
I've been super busy the last few days, so I haven't been able to test it extensively, but it does appear to be fixed. Thanks for the quick response.
