### ISSUE TITLE
Blade directives are not working

### ISSUE THREAD

**Issue by muhammad-adil916** [bgaze/bootstrap-form#7]
I'm unable to render view through blade directive where BF facade is working.
brackets are missing for BF::close, it should be BF::close() in documentation otherwise this would throw an exception (`Undefined class constant 'close'`).

**Comment by bgaze** [comment]
Hi @muhammad-adil916 

This is indeed a typo in the doc : brackets can be omitted with Blade directive when no arguments, so `@close` is valid, but `BF::close()` is a plain PHP function call, so brackets are required.

I've corrected that, thanks for your feedback.
